from .ComplEx import ComplEx
from .TransE import TransE
from .DistMult import DistMult
from .RotatE import RotatE
from .TransH import TransH
from .TransR import TransR
from .SimplE import SimplE
from .BoxE import BoxE
from .ConvE import ConvE
from .CrossE import CrossE
from .HAKE import HAKE
from .PairRE import PairRE
from .DualE import DualE
