ablation: 0
accelerator: null
accumulate_grad_batches: null
add_ht_emb: true
add_traspose_rels: false
adv_temp: 1.0
amp_backend: native
amp_level: null
attn_rel_emb_dim: 32
aug_num_rels: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
axiom_types: 10
axiom_weight: 1.0
benchmark: false
bn: false
calc_hits:
- 1
- 5
- 10
check_per_epoch: 5
check_per_step: 455
check_val_every_n_epoch: 1
checkpoint_callback: null
checkpoint_dir: ''
coef_dgi_loss: 5
comp_ht: sum
comp_op: mul
conc: false
config_path: ''
constrained_neg_prob: 0.0
data_class: KGDataModule
data_path: dataset/FB15K237_v3
dataset_name: FB15K237_v3
db_path: dataset/FB15K237_v3_subgraph
decoder_model: null
default_root_dir: null
detect_anomaly: false
deterministic: false
devices: null
directed: false
dis_order: 2
dropout: 0.0
early_stop_patience: 20
edge_dropout: 0.5
emb_dim: 32
emb_shape: 20
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
enclosing_sub_graph: true
ent_drop: 0.2
ent_drop_pred: 0.3
epoch_GAT: 3000
eval_bs: 16
eval_task: link_prediction
fast_dev_run: false
fc_bias: true
fc_drop: 0.1
fet_drop: 0.2
filter_flag: true
flush_logs_every_n_steps: null
freq_init: 4
gnn_agg_type: sum
gpu: cuda:0
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
has_attn: true
hid_drop: 0.3
hid_size: 9728
hid_size_component: 3648
hop: 3
inductive: true
init_checkpoint: null
init_nei_rels: in
inject_triple_percent: 1.0
inp_dim: 8
inp_drop: 0.2
ipus: null
is_comp: mult
k_h: 10
k_w: 20
ker_sz: 3
kg_layer: 1
kge_model: TransE
l2: 0.0005
label_smooth: 0.1
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
litmodel_name: indGNNLitModel
load_config: false
log_every_n_steps: 50
log_gpu_memory: null
logger: true
loss_name: Margin_Loss
lr: 0.01
margin: 10.0
max_entialments: 2000
max_epochs: 100
max_links: 1000000
max_n_label: null
max_nei_rels: 10
max_nodes_per_hop: null
max_steps: -1
max_time: null
maxsteps: null
min_epochs: null
min_steps: null
model_name: Grail
modulus_weight: 1.0
move_metrics_to_cpu: false
mu: 10
multiple_trainloader_mode: max_size_cycle
neg_weight: 50
negative_adversarial_sampling: true
nei_rel_path: true
nei_rels_dropout: 0.4
norm_flag: false
num_bases: 4
num_batches: 0
num_ent: null
num_layers: 3
num_neg: 100
num_neg_samples_per_link: 1
num_nodes: 1
num_processes: 1
num_rel: null
num_sanity_val_steps: 2
num_train_subgraph: 10000
num_valid_subgraph: 200
num_workers: 20
opn: corr
optim_name: Adam
out_channel: 32
out_dim: 200
overfit_batches: 0.0
partial_2hop: false
path_agg: att
phase_weight: 1.0
pk_path: dataset/FB15K237_v3.pkl
plugins: null
precision: 32
pred_rel_w: false
prepare_data_per_node: null
process_position: 0
profiler: null
progress_bar_refresh_rate: null
reduction: mean
regularization: 0.0
regularization_two: 0
rel_drop: 0
rel_emb_dim: 32
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
rm_rate: 0.5
rw_0: 10
rw_1: 10
rw_2: 5
save_config: false
save_path: logging
seed: 321
select_probability: 0.8
sem_dim: 24
shuffle: true
slackness_penalty: 0.01
smoothing: 0.1
sort_data: true
special_name: null
stochastic_weight_avg: false
strategy: null
sync_batchnorm: false
target2nei_atten: false
terminate_on_nan: null
test_bs: 1
test_db_path: dataset/FB15K237_v3_test_subgraph
test_only: false
test_sampler_class: TestSampler_hit
tpu_cores: null
track_grad_norm: -1
train_bs: 16
train_sampler_class: SubSampler
update_axiom_per: 2
use_kge_embeddings: false
use_wandb: false
use_weight: false
val_check_interval: 1.0
valid_sampler_class: ValidSampler
warm_up_steps: null
warmup_epoch: 5
weight_decay: 0.01
weights_save_path: null
weights_summary: top
